In [8]:
# function to encrypt a data file
keyfile = 'Datafiles/key.txt'
def dictionarykeyfile(keyfile):
    key = {}
    with open(keyfile,'r') as f:
        for line in f:
            line = line.split()
            key[line[0]] = line[1]
    return key
dictionarykeyfile(keyfile)
def encryptmarksdata(datafile,keyfile):
    # construct a dictionary for key data
    key = dictionarykeyfile(keyfile)
    with open(datafile,'r') as f:
        filedata = f.read().split('\n')
    with open('Datafiles/encryptedmarks.txt','w') as f:
        for mark in filedata:
            line = ' '
            for n in mark:
                line += key[n]
            f.write(line+'\n')
    return
datafile = 'Datafiles/marks.txt'
encryptmarksdata(datafile,keyfile)        

In [58]:
keyfile = 'Datafiles/key.txt'
def dictionarykeyfile(keyfile):
    key = {}
    with open(keyfile,'r') as f:
        for line in f:
            line = line.split()
            key[line[0]] = line[1]
    return key
def discryptmarksdata(encryptedfile,keyfile):
    key = dictionarykeyfile(keyfile)
    newkey = {}
    for key,value in key.items():
        newkey[value] = key
    with open(encryptedfile,'r') as f:
        encrypteddata = f.read().split('\n')
    with open('Datafiles/discryptedmarks.txt','w') as f:
        for encryptedmark in encrypteddata:
            line =''
            for n in encryptedmark:
                line += newkey[n]
            f.write(line+'\n')
    return
import timeit
encryptedfile ='Datafiles/encryptedmarks.txt'
st = timeit.default_timer()
discryptmarksdata(encryptedfile,keyfile)
print(timeit.default_timer()-st)

KeyError: ' '

In [22]:
keyfile = 'Datafiles/key.txt'
key = dictionarykeyfile(keyfile)
key

{'4': '0',
 '5': '1',
 '6': '2',
 '7': '3',
 '8': '4',
 '9': '5',
 '0': '6',
 '1': '7',
 '2': '8',
 '3': '9'}

In [20]:
# comperhensions

keyfile = 'Datafiles/key.txt'
key = dictionarykeyfile(keyfile)
evenkeys = {item for item in key.items() if int(item[0])%2 == 0}
evenkeys

{('0', '6'), ('2', '8'), ('4', '0'), ('6', '2'), ('8', '4')}

In [21]:
keyfile = 'Datafiles/key.txt'
key = dictionarykeyfile(keyfile)
evenkeys = {item for item in key}
evenkeys

{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}

## Numpy library


- Processing N-Dimensional arrays

In [24]:
import numpy as np

li = [1,2,3]

a = np.array(li)
a

array([1, 2, 3])

In [8]:
import numpy as np

li = [1,2,3, 'z']

a = np.array(li)
a

array(['1', '2', '3', 'z'], dtype='<U11')

In [5]:
import numpy as np

li = [1,2,3, 'z']

a = np.array(li)

b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
rn = np.random.randint(0,100, size=10)
rn

array([ 6, 72, 21, 13, 15, 67, 38,  5, 20, 26])

In [25]:
m3 = np.random.randint(0,2,size=(3,3,2,4))
m3

array([[[[0, 1, 1, 1],
         [0, 0, 0, 1]],

        [[1, 1, 1, 0],
         [0, 0, 0, 0]],

        [[0, 1, 1, 1],
         [1, 1, 0, 1]]],


       [[[0, 1, 1, 1],
         [0, 0, 0, 0]],

        [[0, 1, 1, 0],
         [0, 0, 1, 0]],

        [[0, 1, 1, 1],
         [1, 1, 1, 0]]],


       [[[1, 0, 1, 0],
         [1, 0, 1, 0]],

        [[1, 0, 0, 1],
         [0, 0, 1, 1]],

        [[1, 0, 0, 1],
         [1, 0, 1, 0]]]])

In [27]:
m3 = np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]

1

In [28]:
m3.ndim
m3.size
m3.shape

(3, 3, 3, 3)

In [31]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes

324

In [33]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [36]:
print(a)

['1' '2' '3' 'z']


In [38]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Pandas

- Data cleaning
- Data tranformation
- Data analysis

Notations

- Series
- Dataframes

In [4]:
import pandas as pd

internal1 = {'s1':21,'s2':18,'s3':24}

internal1 = pd.Series(internal1)
internal2 = {'s1':15,'s2':20,'s3':23}
internal2 = pd.Series(internal2)
internal2

s1    15
s2    20
s3    23
dtype: int64

In [9]:
final = {'Internal1':internal1,'Internal2':internal2}

final = pd.DataFrame(final)
final

Internal1  Internal2
s1         21         15
s2         18         20
s3         24         23

In [8]:
final = {'Internal1':internal1,'Internal2':internal2}

final = pd.DataFrame(final)
final['Internal1']

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [10]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [11]:
final.values # list of all rows

array([[21, 15],
       [18, 20],
       [24, 23]], dtype=int64)

In [12]:
final.values[2]

array([24, 23], dtype=int64)

In [13]:
final.values[2,0]

24

In [15]:
for row in final.values:
    print('Internal1-',row[0],',Internal2-',row[1])

Internal1- 21 ,Internal2- 15
Internal1- 18 ,Internal2- 20
Internal1- 24 ,Internal2- 23


In [17]:
final.loc['s4'] = [17,19]
final

Internal1  Internal2
s1         21         15
s2         18         20
s3         24         23
3          15         18
s4         17         19

In [18]:
final.drop(3)

Internal1  Internal2
s1         21         15
s2         18         20
s3         24         23
s4         17         19

In [20]:
final.values[2] = [12,25]
final

Internal1  Internal2
s1         21         15
s2         18         20
s3         12         25
3          15         18
s4         17         19

In [21]:
final = final.drop(3)
final

Internal1  Internal2
s1         21         15
s2         18         20
s3         12         25
s4         17         19

In [24]:
# reading csv file data
import pandas as pd
filepath = 'Datafiles/income.csv'
incomedf = pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [25]:
# extract income of all states in 2003
# california : 57528
for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [26]:
# average income of arizona

sum = 0
for i in range(2,11):
    sum += incomedf.values[2][i]
sum/len(incomedf.values[2][2:])

47214.77777777778

In [27]:
# average income of all states in year 2012
sum = 0
for row in incomedf.values:
    sum += row[-2]
sum/len(incomedf.values)


50038.8